export interface TrackDefinition {
  id: string
  code: 'DS' | 'AI' | 'HA' | 'CS' | 'BA' | 'MA'
  name: string
  subjects: string[]
}

export const ACADEMIC_TRACKS: TrackDefinition[] = [
  {
    id: 'DS',
    code: 'DS',
    name: 'Data Science (DS)',
    subjects: [
      'Advanced Calculus',
      'Advanced Database Systems',
      'Big Data Analytics',
      'Calculus',
      'Cloud Computing',
      'Computer Networks',
      'Computing Intensive Statistical Methods',
      'Critical Thinking',
      'Data Computation and Analysis',
      'Data Mining and Analytics',
      'Data Science Methodology',
      'Data Science Tools and Software',
      'Data Structures and Algorithms',
      'Data Visualization Tools',
      'Design and Analysis of Experiments',
      'Discrete Structures',
      'Dist Processing',
      'Distributed Data Analysis',
      'Economy Science',
      'First Aids',
      'Fitness and Health',
      'Innovation & Entrepreneurship',
      'Introduction to Artificial Intelligence',
      'Introduction to Computer Systems',
      'Introduction to Data Sciences',
      'Introduction to Databases',
      'Introduction to Social Networks',
      'Linear Algebra',
      'Machine Learning',
      'Math 0',
      'Modern Tourism',
      'Numerical Computations',
      'Operating Systems',
      'Pet Handeling',
      'Probability and Statistics I',
      'Probability and Statistics II',
      'Programming I',
      'Programming II',
      'Regression Analysis',
      'Simulations',
      'Social Data Analytics',
      'Software Engineering',
      'Stochastic Processes',
      'Stream Processing',
      'Survey Methodology',
      'System Analysis and Design',
      'Web Programming'
    ]
  },
  {
    id: 'AI',
    code: 'AI',
    name: 'Artificial Intelligence (AI)',
    subjects: [
      'AI Platforms',
      'AI Security Issues',
      'AI for Robotics',
      'Calculus',
      'Cloud Computing',
      'Computer Vision',
      'Critical Thinking',
      'Data Mining and Analytics',
      'Data Structures and Algorithms',
      'Deep Learning',
      'Discrete Structures',
      'Economy Science',
      'Embedded Systems',
      'Innovation & Entrepreneurship',
      'Intelligent Programming',
      'Internet of Things I',
      'Introduction to Artificial Intelligence',
      'Introduction to Computer Systems',
      'Introduction to Data Sciences',
      'Introduction to Databases',
      'Linear Algebra',
      'Machine Learning',
      'Modern Control Systems',
      'Natural Language Processing',
      'Neural Networks',
      'Numerical Computations',
      'Operations Research',
      'Pattern Recognition',
      'Probability and Statistics I',
      'Probability and Statistics II',
      'Programming I',
      'Programming II',
      'Reinforcement Learning',
      'Smart Systems and Computational Intelligence',
      'Visual Recognition'
    ]
  },
  {
    id: 'HA',
    code: 'HA',
    name: 'Healthcare Analytics (HA)',
    subjects: [
      'Anatomy and Physiology',
      'Calculus',
      'Clinical & Medical Care Delivery',
      'Clinical Decision Support Systems',
      'Cloud Computing',
      'Computer-Assisted Drug Design',
      'Computerized Disease Registries',
      'Critical Thinking',
      'Data Mining and Analytics',
      'Data Structures and Algorithms',
      'Discrete Structures',
      'E-health, Telehealth and Telemedicine',
      'Ethics & Regulations in Healthcare',
      'Health Information Systems',
      'Health Policy & Economics',
      'Health Psychology',
      'Healthcare Market Analytics',
      'Innovation & Entrepreneurship',
      'Introduction to Artificial Intelligence',
      'Introduction to Computer Systems',
      'Introduction to Data Sciences',
      'Introduction to Databases',
      'Introduction to Epidemiology',
      'Linear Algebra',
      'Machine Learning',
      'Mathematical Modelling for Health',
      'National and International Healthcare Systems',
      'Neuroscience and Robotics',
      'Numerical Computations',
      'Pharmacology and Chemistry of Drugs',
      'Probability and Statistics I',
      'Probability and Statistics II',
      'Programming I',
      'Programming II'
    ]
  },
  {
    id: 'CS',
    code: 'CS',
    name: 'Cybersecurity (CS)',
    subjects: [
      'Calculus',
      'Cloud Computing',
      'Computer Networks',
      'Computer and Network Security',
      'Critical Thinking',
      'Cryptography',
      'Cybersecurity Risk Management',
      'Data Integrity and Authentication',
      'Data Mining and Analytics',
      'Data Structures and Algorithms',
      'Digital Forensics',
      'Discrete Structures',
      'Economy Science',
      'Human Security',
      'Information Security Management',
      'Innovation & Entrepreneurship',
      'Introduction to Artificial Intelligence',
      'Introduction to Computer Systems',
      'Introduction to Cybersecurity',
      'Introduction to Data Sciences',
      'Introduction to Databases',
      'Law and Cybersecurity',
      'Linear Algebra',
      'Machine Learning',
      'Number Theory',
      'Numerical Computations',
      'Operating Systems',
      'Operating Systems Security',
      'Probability and Statistics I',
      'Probability and Statistics II',
      'Programming I',
      'Programming II',
      'Secure Software Development',
      'Security of Distributed Systems',
      'Social Network Computing'
    ]
  },
  {
    id: 'BA',
    code: 'BA',
    name: 'Business Analytics (BA)',
    subjects: [
      'Accounting as an Information Systems',
      'Advanced Calculus',
      'Business Process Modeling and Integration',
      'Calculus',
      'Cloud Computing',
      'Critical Thinking',
      'Data Driven Marketing',
      'Data Mining and Analytics',
      'Data Science Methodology',
      'Data Structures and Algorithms',
      'Data Visualization',
      'Data Warehousing & Business Intelligence',
      'Data and IT Governance',
      'Discrete Structures',
      'Economy Science',
      'Enterprise Information Systems',
      'Financial Planning and Analysis',
      'Information Retrieval',
      'Information Technology Laws and Ethics',
      'Innovation & Entrepreneurship',
      'Introduction to Artificial Intelligence',
      'Introduction to Business',
      'Introduction to Computer Systems',
      'Introduction to Data Sciences',
      'Introduction to Databases',
      'Leadership and People Analytics',
      'Linear Algebra',
      'Logistics and Supply Chain Analytics',
      'Machine Learning',
      'Numerical Computations',
      'Probability and Statistics I',
      'Probability and Statistics II',
      'Programming I',
      'Programming II',
      'Quantitative Analysis',
      'System Analysis & Design',
      'Text and Social Media Mining'
    ]
  },
  {
    id: 'MA',
    code: 'MA',
    name: 'Media Analytics (MA)',
    subjects: [
      'Audience Research and Analysis',
      'Calculus',
      'Cloud Computing',
      'Computer Audio',
      'Computer Graphics',
      'Critical Thinking',
      'Data Driven Journalism',
      'Data Mining and Analytics',
      'Data Structures and Algorithms',
      'Digital Broadcasting',
      'Digital Mass Communication',
      'Digital Video Production',
      'Discrete Structures',
      'Economy Science',
      'Image Processing',
      'Infographics and Data Visualization',
      'Innovation & Entrepreneurship',
      'Introduction to Artificial Intelligence',
      'Introduction to Computer Systems',
      'Introduction to Data Sciences',
      'Introduction to Databases',
      'Linear Algebra',
      'Machine Learning',
      'Media Processing',
      'Multimedia Analytics',
      'Natural Language Processing',
      'News Editing and Blogging',
      'Numerical Computations',
      'Probability and Statistics I',
      'Probability and Statistics II',
      'Programming I',
      'Programming II',
      'Public Opinion and E Surveys',
      'Social Media Analytics',
      'Web Design and Search-Engine Optimization'
    ]
  }
]

export const ALL_SUBJECTS_LIST = Array.from(
  new Set(ACADEMIC_TRACKS.flatMap(t => t.subjects))
).sort()
